version: '3.9'
services:
  node-app:
    build: .
    ports:
      - 3000:3000
    environment:
      - PORT=3000
    depends_on:
      - mongo
  
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=sachin
      - MONGO_INITDB_ROOT_PASSWORD=sachin
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db: