version: '3.9'
services:
  node-app:

    build: 
      context: .
      args:
        NODE_ENV: development

    volumes:
      - ./:/app
      - /app/node_modules

    environment:
      - NODE_ENV=development
      - MONGO_USER=sachin
      - MONGO_PASSWORD=sachin

    command: npm run dev
  
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=sachin
      - MONGO_INITDB_ROOT_PASSWORD=sachin
    